### ISSUE TITLE
No Documentation on Installation method.

### ISSUE THREAD

**Issue by SpiroExDeus** [drxzcl/chrome-send-to-ifttt#3]
Bearing in mind we're not all expert plugin programmers it would be nice to have a part of the readme on how and where to install the files to get this working as a Chrome plugin.

Information on how/whether this would work on other Chromium based browsers would also be helpful.

**Comment by SpiroExDeus** [comment]
As a side note, I am familiar with various forms of coding but am only just getting the knack of github.

As this appears an open project I will be cloning the repo, working out installation to chrome &/or Opera and testing it. If all goes well I should also be able to update the documentation regarding installing to browser and differences between the Maker Channel and webhooks  (If the differences are anything more than a rename).

**Comment by drxzcl** [comment]
This extension will not install on current versions of Chrome. It's about 5 years out of date.

**Comment by SpiroExDeus** [comment]
Oh.. biscuits.
